version: '2'

services:
  python: &python
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV}
    image: joanfont/grissom:latest
    links:
      - mongo
    env_file:
      - ../.env
    volumes:
      - "../:/code"

  mongo:
    image: library/mongo:3.4.2
    volumes:
      - "/opt/grissom/mongo:/data/db"
    ports:
      - "7777:27017"

  rabbit:
    image: library/rabbitmq:3.6.6-alpine

  worker: &worker
    <<: *python
    links:
      - mongo
      - rabbit
    entrypoint: ["celery"]
    command: ["worker", "-A", "async.celery"]

  beat:
    <<: *worker
    links:
      - worker
    command: ["beat", "-A", "async.celery",  "--loglevel=debug", "--pidfile="]

  scrapy:
    <<: *python
    links:
      - mongo
      - worker
    entrypoint: ["scrapy"]

  tests:
    <<: *python
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_ENV: test
    image: joanfont/grissom:tests
    entrypoint: ["py.test"]
